name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.0

      # TODO: We should solve the problem as follows later
      # error https://registry.yarnpkg.com/har-schema/-/har-schema-2.0.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open '/home/runner/.cache/yarn/v6/npm-har-schema-2.0.0-a94c2224ebcac04782a0d9035521f24735b7ec92-integrity/node_modules/har-schema/lib/header.json'"

      # - name: Run install
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: install # will run `yarn install` command

      # - name: Build
      #   run: npm run build

      # - name: Run tests
      #   run: npm run test
